mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('detail/', views.DetailView.as_view(), name='detail'),
    path('finish/',views.finish,name='finish'),

    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    correct=models.IntegerField(default=0)

    def __str__(self):
        return str(self.question_text)+"   "+str(self.correct)
    #def __str__(self):
        #return self.correct


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    answer= models.CharField(max_length=200)
    #def ans(self):
    #    return(str(self.answer))
    def __repr__(self):
       return ((self.votes))

class Correct(models.Model):
    answer=models.CharField(max_length=100)
    no_of_correct=models.IntegerField()

    def __str__(self):
        return(self.answer)

mysite/polls/views.py
from django.http import HttpResponse

from django.shortcuts import render

from .models import Question
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question
from django.utils import timezone
from django.urls import reverse



from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question,Correct


class IndexView(generic.ListView):
    model=Question

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'


    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[::-1]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# ...
def finish(request):

    #sc=selected_choice.votes
    sum=0
    for choice in Question.objects.all():
           sum+=int(choice.correct)

    sc=sum

    return render(request, "polls/finish.html",context={"sc":sc})

def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    selected_choice = question.choice_set.get(pk=request.POST['choice'])


    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:

        #return HttpResponse(question.correct)
        if str(selected_choice.choice_text)==str(selected_choice.answer):
            selected_choice.votes += 1
            selected_choice.save()
            question.correct+=1
            question.save()
            fl=True
            sc=selected_choice.votes
            #Correct.no_of_correct+=1
            #Correct.save()
            #return HttpResponse(sc)
            #return render(request,'polls/results.html',context={"fl":"fl" , "selected_choice":"selected_choice"})
            #finish(request,sc)
            #return render(request,'polls/results.html',context={"fl":"fl","sc":sc})
            #return HttpResponseRedirect(reverse('polls:results',context={"fl":"fl","selected_choice":"selected_choice"},args=(question.id,)))

        #return HttpResponse(str(selected_choice.choice_text)+"  "+str(selected_choice.answer))

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.

        return render(request,'polls/index.html')
        #return HttpResponseRedirect(reverse('polls:index', args=(question.id,)))

mysite/polls/templates/polls/base.html
<html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<nav class="navbar navbar-expand-sm bg-light navbar-primary">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">MCQ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">TESTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Placement</a>
      </li>
      
    </ul>
  </nav>


  </html>

mysite/polls/templates/polls/detail.html
 
{% block content %}
 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<div style="margin-top: 50px;"> 
    <h1>hello</h1>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>

<button type="button" class="btn btn-primary" >{{question.id}}</button>

</form>
</div>
{% endblock %}

mysite/polls/templates/polls/finish.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <h1 style="color:green">
<div class="jumbotron">
      Your score is {{ sc }} marks</h1>
      Thanks for taking the test
      </div>

  </body>
</html>

mysite/polls/templates/polls/index.html

 {% load static %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<nav class="navbar navbar-expand-sm bg-light navbar-primary">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">MCQ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">TESTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Placement</a>
      </li>

    </ul>
  </nav>

<div style="margin-top: 50px;">
{% if latest_question_list %}
    <ol>
    {% for question in latest_question_list %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <li>{{ question.question_text }}</li>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {{ fl }}
    {% endfor %}
    <input type="submit" value="Answer">
    </form>

    {% endfor %}

  <h3>Check whether you have attended all the questions and then finish the test</h3>
    <a href="{% url 'polls:finish' %}" class="btn-btn-primary">Finish</a>

    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

{% endblock %}

mysite/polls/templates/polls/results.html


{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<div style="margin-top: 50px;">
  <h1>{{ question.question_text }}</h1>

{% if fl %}

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
    <h3 style="color: green">   {{ sc }}    Correct Answer</h3>
{% else %}
     <h3 style="color: red">Wrong Answer</h3>
{% endif %}



</div>
{% endblock %}