testproject/testproject/testapp/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
from django.conf.urls import url
from testapp.views import  GeneratePDF
app_name = 'testapp'

urlpatterns = [
    path('',views.index,name="index"),
    path('thanos/',GeneratePDF.as_view(),name="GeneratePDF"),
    url(r'^signup/$', views.register, name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
        url(r'^user_login/$',views.user_login,name='user_login'),
    path('home/',views.home,name="home"),
    path('quiz1/',views.quiz1,name="quiz1"),
    path('quiz2/',views.quiz2,name="quiz2"),
    path('<int:user_id>/finish1/',views.finish1,name='finish1'),
    path('<int:user_id>/finish2/',views.finish2,name='finish2'),
    path('<int:user_id>/finish/',views.finish,name='finish'),
    #path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote1/', views.vote1, name='vote1'),
    path('<int:question_id>/vote2/',views.vote2,name='vote2'),
        #url(r'^<int:pk>/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
    path('documents/',views.document,name="document"),
]

testproject/testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('testapp.urls', namespace='testapp')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('testapp.urls', namespace='testapp')),
    path('admin/', admin.site.urls),
]

testproject/testproject/testapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    scores = models.IntegerField(default=0)

    def __str__(self):
        return(str(self.user)+" has scored "+str(self.scores)+" marks")

class Quiz1(models.Model):
    question_text = models.CharField(max_length=100)
     
    correct= models.CharField(max_length=200)

    def __str__(self):
        return str(self.question_text)+" "+str(self.correct)

class Choice(models.Model):
    question = models.ForeignKey(Quiz1, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __repr__(self):
       return ((self.votes))

class Quiz2(models.Model):
    question_text = models.CharField(max_length=100)
     
    correct= models.CharField(max_length=200)

    def __str__(self):
        return str(self.question_text)+" "+str(self.correct)
class Choice2(models.Model):
    question = models.ForeignKey(Quiz2, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __repr__(self):
       return ((self.votes))
class Profile1(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    scores = models.IntegerField(default=0)

    def __str__(self):
        return(str(self.user)+" has scored "+str(self.scores)+" marks in quiz1")

class Profile2(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    scores = models.IntegerField(default=0)

    def __str__(self):
        return(str(self.user)+" has scored "+str(self.scores)+" marks in quiz1")

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return(str(self.description))




testproject/testproject/testapp/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','password','email','first_name', 'last_name')

testproject/testproject/testapp/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import render,redirect
from testapp.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from testapp.models import Quiz1,Profile,Choice,Quiz2,Choice2,Profile1,Profile2,Document
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.template.loader import get_template 
from django.contrib.sessions.models import Session
from django.contrib.sessions.backends.db import SessionStore
from testproject.utils import render_to_pdf #created in step 4

from django.core import serializers

l=[];sum1=0;sum2=0;sum=0;l1=[]
count=0
count1=0
count2=0
s1=0
cat=[];dog=[]


class GeneratePDF(View):
    def get(self, request,*args, **kwargs):
         if request.user.is_superuser:
           template = get_template('finish.html')
           pro=Profile.objects.all()
           context = {
               "pro":pro
            }
           html = template.render(context)
           pdf = render_to_pdf('finish.html', context)
           if pdf:
              response = HttpResponse(pdf, content_type='application/pdf')
              filename = "results_%s.pdf" %("12341231")
              content = "inline; filename='%s'" %(filename)
              download = request.GET.get("download")
              if download:
                  content = "attachment; filename='%s'" %(filename)
              response['Content-Disposition'] = content
              return response
           return HttpResponse("Not found")
         else:
             return HttpResponse("Page doesnot exists")

# Create your views here.
def index(request):
    return render(request,'index.html')

@login_required
def home(request):
  
   return render(request,'home.html')

@login_required
def document(request):
    documents=Document.objects.all()
    return render(request,'document.html',{"documents":documents})


@login_required
def user_logout(request):
    logout(request)
    return render(request,'index.html')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            user.is_active = False
            current_site = get_current_site(request)
            mail_subject = 'Activate your quiz account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            #return HttpResponse(to_email)
            email.send()
            return render(request,'acc_active_sent.html')
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'registered':registered})

def activate(request, uidb64, token):
         try:
             uid = force_text(urlsafe_base64_decode(uidb64))
             user = User.objects.get(pk=uid)
             #return HttpResponse(user)
         except(TypeError, ValueError, OverflowError, User.DoesNotExist):
               user = None
         user.is_active = True
        
         user.save()
         login(request, user)
                  # return redirect('home')
         return render(request,'login.html',{'user_login':user_login})

def user_login(request):
           if request.method == 'POST':
                username = request.POST.get('username')
                password = request.POST.get('password')
                #scores=user.scores
                user = authenticate(username=username, password=password)
                if user:
                    if user.is_active:

                          login(request,user)
                         
                          return render(request,'home.html')
                    else:
                          return HttpResponse("Your account was inactive.")
                else:
                    print("Someone tried to login and failed.")
                    print("They used username: {} and password: {}".format(username,password))
                    return HttpResponse("Invalid login details given")
           else:
                 return render(request, 'login.html', {})
def finish1(request,user_id):
    global sum1
    l2=[]
    sc=sum1
    c = User.objects.get(pk=user_id)
  
    pr=Profile1()
    pr.user=c
    pr.scores=sum1
    for pro in Profile1.objects.all():
        l1.append(str(pro.user))
    if str(c) not in l1:
        pr.save()
 
 
    pro=Profile1.objects.all()
    return render(request, "finish1.html",context={"sc":sc,"pro":pro})

def finish2(request,user_id):
    d=[]
 
    c = User.objects.get(pk=user_id)

    pr = Profile2()
    global sum2
    pr.user=c
    pr.scores=sum2
    sc=sum2
    for pro in Profile2.objects.all():
        d.append(str(pro.user))
    if str(c) not in d:
        pr.save()


    pro=Profile2.objects.all()
    return render(request, "finish2.html",context={"sc":sc,"pro":pro})
def finish(request,user_id):
    d1=[];d2=[]
    global s1
    s2=0
    c = User.objects.get(pk=user_id)
    pr = Profile()
    pr.user=c
  
    for pro in Profile1.objects.all():
           if str(c)==str(pro.user):
               s2+=int(pro.scores)
               break
    for p in Profile2.objects.all():
            if str(c)==str(p.user):
                s2+=int(p.scores)
    pr.scores=s2
    sc=s2
    for pro in Profile.objects.all():
        d1.append(str(pro.user))
    if str(c) not in d1:
           pr.save()
    pro=Profile.objects.all()
    for pr in Profile.objects.all():
        cat.append(str(pr.user))
        dog.append(str(pr.scores))
    pr=Profile.objects.all()
    p1=Profile1.objects.all()
    p2=Profile2.objects.all()
    return render(request, "finish.html",context={"sc":sc,"pro":pro,"pr":pr,"p1":p1,"p2":p2})

@login_required
def quiz1(request):
    latest_question_list = Quiz1.objects.all()
    return render(request,'quiz1.html',context={"latest_question_list":latest_question_list})


@login_required
def quiz2(request):
    latest_question_list = Quiz2.objects.all()
    return render(request,'quiz2.html',context={"latest_question_list":latest_question_list})
def vote1(request, question_id):
    question = get_object_or_404(Quiz1, pk=question_id)
    global s1           
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Quiz1.DoesNotExist):

        return render(request, 'index.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        s=question.correct
        global sum1
        if question not in l:
                if str(selected_choice.choice_text)==str(s):
                   fl=True
                    
                   sum1+=1
                   s1+=1
                   l.append(question)

        sc=sum1
           
        return render(request,'results.html',context={"sc":sc})

def vote2(request, question_id):
    question = get_object_or_404(Quiz2, pk=question_id)
    global s1            
    selected_choice = question.choice2_set.get(pk=request.POST['choice'])
    try:
        selected_choice = question.choice2_set.get(pk=request.POST['choice'])
    except (KeyError, Quiz2.DoesNotExist):
        return render(request, 'index.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        s=question.correct
        global sum2
        if question not in l:
                if str(selected_choice.choice_text)==str(s):
                   fl=True 
                   sum2+=1
                   s1+=1
                   l.append(question)
        sc=sum2
        return render(request,'results.html',context={"sc":sc})


       


testproject/testproject/testapp/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'testapp:activate' uidb64=uid token=token %}
{% endautoescape %}

testproject/testproject/testapp/templates/acc_active_sent.html
<!DOCTYPE html>
{% block content %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body style="background-color:green">

      <h1 style="color:white" >

      <center>Please confirm your email address to complete the registration.</center></h1>


  </body>
</html>
  {% endblock %}

testproject/testproject/testapp/templates/document.html
{% extends "index.html" %}
{% block body_block %}
<ul>
    {% for obj in documents %}
      <li>
        <a href="{{ obj.document.url }}" class="btn btn-primary" >{{ obj.document.name }}</a>
        <small>(Uploaded at: {{ obj.uploaded_at }})</small>
      </li>
    {% endfor %}
  </ul>

  {% endblock %}

testproject/testproject/testapp/templates/finish1.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://use.fontawesome.com/54b5365f0e.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>


  <style type="text/css">

  .fa {
  padding: 20px;
  font-size: 30px;
  width: 64px;
  text-align: center;
  text-decoration: none;
  border-radius: 70%;
  }


  /* Add a hover effect if you want */
  .fa:hover {
  opacity: 0.7;
  }

  /* Set a specific color for each brand */

  /* Facebook */
  .fa-facebook {
  background: #3B5998;
  color: white;
}


  /* Twitter */
  .fa-twitter {
  background: #55ACEE;
  color: white;
  }

  .fa-linkedin{
    background: #0066ff;
    color: white;
  }


  </style>

  </head>





  <body>
    <div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=447635729356838&autoLogAppEvents=1"></script>


    <h1 style="color:green">
<div class="jumbotron">
      Your score is {{ sc }} marks</h1>

      Thanks for taking the test



              <div class="container">
                <h3>LeaderBoard</h3>


              <table class="table table-sm table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Score</th>

    </tr>
  </thead>
  <tbody>
    {% for data in pro %}
    <tr>


      <td>{{ data.user }}</td>
      <td>{{ data.scores }}</td>

    </tr>
    {% endfor %}

              </table>
                </div>



            



      <div class="container">
        <h1> Share your results</h1>
      <a class="twitter-share-button fa fa-twitter"
      href="https://twitter.com/intent/tweet?text=Ihavescored{{sc}}marks"
      data-size="large">
    </a>
    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Fthirumalai.srinivasan.148&amp;src=sdkpreparse" class="fa fa-facebook fb-xfbml-parse-ignore"></a>

    <a href="https://platform.linkedin.com/in.js" class="fa fa-linkedin"><script type="IN/Share" data-url="https://www.linkedin.com/in/thirumalai-s-13a824148/"></script></a>

  </div>

  <a href="{% url 'testapp:home' %}" class="btn btn-primary">Back to Home</a>
  </body>
</html>

testproject/testproject/testapp/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title>design</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



    <nav class="navbar navbar-dark bg-primary">
        <div class="col">
            Django
        </div>
        <div class="col-1">
            <a to="/homepage" class="navbar-brand" href="{% url 'admin:index'  %}">
                Admin
            </a>
        </div>

        <div class="col-1">
            <a to="/topics" class="navbar-brand" href="{% url 'testapp:document'  %}">
             Notes
            </a>
        </div>

            <div class="col-1">
                 <a to="/login" class="navbar-brand" href="{% url 'testapp:user_logout'  %}">
                      Logout
                  </a>

    </nav>

</head>

<body>
    <div class="container">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="container">
                <h1>Welcome {{ user.username }}</h1>
                <h2>your scores {{ user.scores }}</h2>
                <br>
                <div class="row">

                    <button type="submit" class="btn quiz-button col">
                        <a class="button-text" href="{% url 'testapp:quiz2' %}">
                            Aptitude Quiz
                            <img class="quiz-icons" src="https://image.flaticon.com/icons/svg/478/478540.svg">
                        </a>
                    </button>

                    <button type="submit" class="btn quiz-button col">
                        <a class="button-text" href="{% url 'testapp:quiz1' %}">
                            Verbal Quiz
                            <img class="quiz-icons" src="http://chittagongit.com/download/119957">
                        </a>
                    </button>
                </div>
                <br>
                <div class="row">
                    <button type="submit" class="btn quiz-button col">
                        <a class="button-text" to="/reasoning">
                            Reasoning Quiz
                            <img class="quiz-icons" src="https://image.flaticon.com/icons/svg/470/470274.svg">
                        </a>
                    </button>

                    <button type="submit" class="btn quiz-button col">
                        <a class="button-text" to="/dbms">
                            DBMS Quiz
                            <img class="quiz-icons" src="https://image.flaticon.com/icons/svg/149/149205.svg">
                        </a>
                    </button>
                </div>
                <br>
                <h2>After completing the all the quizzes<br><a href="{% url 'testapp:finish' user.id %}"> click here to
                        get your full score</a></h2>
            </div>
        </div>
    </div>
    </div>
    </div>

</body>

</html>

<style>
    body {
        background-color: rgb(142, 187, 247);
    }

    .navbar {
        color: white;
    }

    .navbar .col {
        margin: auto 10px;
        letter-spacing: 10px;
        font-size: 25px;
        font-family: Impact, Haettenschweiler, "Arial Narrow Bold", sans-serif;
    }


    h1 {
        color: white;
        font-size: 60px;
        padding: 10px;
        text-align: center;
    }

    h2 {
        color: white;
        font-size: 30px;
        padding: 10px;
        text-align: center;
    }

    .quiz-button {
        width: 100%;
        height: 20vh;
        margin: 20px;
        background-color: rgb(247, 251, 255);
        font-size: 30px;
    }

    .quiz-icons {
        height: 80px;
        width: 80px;
        margin: 15px;
    }

    .button-text {
        color: rgb(0, 0, 0);
        text-decoration: none;
    }

    a {
        color: white;
    }

    a:hover {
        color: white;
    }
</style>

testproject/testproject/testapp/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
      <nav class="navbar navbar-dark bg-primary">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="
          C:\Users\user\Desktop\django2\testproject\testapp\templates\index.html" style="color: white">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'testapp:home' %}" style="color: white;">Home</a></li>
          <li><a class="navbar-link" href="{% url 'testapp:register' %}" style="color: white;">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'testapp:user_logout' %}" style="color: white;">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'testapp:user_login' %}" style="color: white;">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

testproject/testproject/testapp/templates/quiz1.html
{% extends "index.html" %}
{% block body_block %}

{% if user.is_authenticated %}



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<div style="margin-top: 50px;">
<style>
#demo {
text-align: right;
font-size: 20px;
padding-left:"60px";
background-color:#f2f2f2

}
body{
  font-size:22px;
}
</style>
<body>
<p id="demo"></p>
<script>
var today = new Date();
var dd = String(today.getDate()).padStart(2, '0');
var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
var yyyy = today.getFullYear();

today = mm + ' ' + dd+', ' + yyyy;
document.write(today);
var deadline = new Date(today+" 23:58:15").getTime();
var x = setInterval(function() {
var now = new Date().getTime();
var t = deadline - now;
var days = Math.floor(t / (1000 * 60 * 60 * 24));
var hours = Math.floor((t%(1000 * 60 * 60 * 24))/(1000 * 60 * 60));
var minutes = Math.floor((t % (1000 * 60 * 60)) / (1000 * 60));
var seconds = Math.floor((t % (1000 * 60)) / 1000);
document.getElementById("demo").innerHTML = days + "d "
+ hours + "h " + minutes + "m " + seconds + "s ";
if (t < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML="EXPIRED";
    flag=1
    window.location.replace("{% url 'testapp:finish' user.id %}");
}
}, 1000);
</script>



<ol>
{% for question in latest_question_list %}
 
<li>{{ question.question_text }}</li>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'testapp:vote1' question.id %}" method="post">
{% csrf_token %}

{% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {{ fl }}
{% endfor %} 
 <div>

<p>you can answer only once<p>
<input type="submit" value="Answer" class="btn btn-success">
</form>

{% endfor %}

<h3>Check whether you have attended all the questions and then finish the test</h3>

<button type="button" class="btn btn-primary"><a href="{% url 'testapp:finish1' user.id %}" style="color:white">Finish</a></button>
</ol>

</div>
{% endif %}
{% endblock %}


testproject/testproject/testapp/templates/quiz2.html
{% extends "index.html" %}
{% block body_block %}

{% if user.is_authenticated %}



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<div style="margin-top: 50px;">
<style>
#demo {
text-align: right;
font-size: 20px;
padding-left:"60px";
background-color:#f2f2f2

}
body{
  font-size:22px;
}
</style>
<body>
<p id="demo"></p>
<script>
var today = new Date();
var dd = String(today.getDate()).padStart(2, '0');
var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
var yyyy = today.getFullYear();

today = mm + ' ' + dd+', ' + yyyy;
document.write(today);
var deadline = new Date(today+" 19:58:15").getTime();
var x = setInterval(function() {
var now = new Date().getTime();
var t = deadline - now;
var days = Math.floor(t / (1000 * 60 * 60 * 24));
var hours = Math.floor((t%(1000 * 60 * 60 * 24))/(1000 * 60 * 60));
var minutes = Math.floor((t % (1000 * 60 * 60)) / (1000 * 60));
var seconds = Math.floor((t % (1000 * 60)) / 1000);
document.getElementById("demo").innerHTML = days + "d "
+ hours + "h " + minutes + "m " + seconds + "s ";
if (t < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML="EXPIRED";
    flag=1
    window.location.replace("{% url 'testapp:finish' user.id %}");
}
}, 1000);
</script>



<ol>
{% for question in latest_question_list %}
 
<li>{{ question.question_text }}</li>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'testapp:vote2' question.id %}" method="post">
{% csrf_token %}
 {% for choice in question.choice2_set.all %}

 <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
 <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
 {{ fl }}
{% endfor %} 

   
 
  
 <div>

<p>you can answer only once<p>
<input type="submit" value="Answer" class="btn btn-success">
</form>

{% endfor %}

<h3>Check whether you have attended all the questions and then finish the test</h3>

<button type="button" class="btn btn-primary"><a href="{% url 'testapp:finish2' user.id %}" style="color:white">Finish</a></button>
</ol>

</div>

{% endif %}

{% endblock %}